format = """\
    $env_var\
    $battery\
    $time\
    $username\
    $hostname\
    $kubernetes\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $docker_context\
    $memory_usage\
    $aws\
    $crystal\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $character\
"""
    #$package\
    #$dotnet\
    #$elixir\
    #$elm\
    #$erlang\
    #$golang\
    #$java\
    #$julia\
    #$nim\
    #$nodejs\
    #$ocaml\
    #$php\
    #$purescript\
    #$python\
    #$ruby\
    #$rust\
    #$terraform\
    #$zig\
    #$nix_shell\
    #$conda\

[env_var]
variable = "STARSHIP_SHELL"
format = "[$env_value]($style) "

[username]
show_always = true
format = "via [$user]($style) "
style_user = "underline 35"

[hostname]
ssh_only = false
style = "underline 38"
format = "on [$hostname]($style) "

[directory]
style = "underline 139"
format = "in [$path]($style)[$read_only]($read_only_style) "

[cmd_duration]
style = "yellow"

[character]
style_success = "bold 77"
style_failure = "bold 161"
symbol = ""
vicmd_symbol = ""

[time]
style = "underline 139"
format = "at [$time]($style) "
disabled = false

[battery]
discharging_symbol = "⇣ "
charging_symbol = "⇡ "
full_symbol = "• "

[[battery.display]]
threshold = 100
style = "green"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "yellow"

[golang]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[git_branch]
style = "underline 149"

[git_status]
separator = "|"
style = "bold 250"
modified = "[$count ✎ ](yellow) "
untracked = "[$count ](161) "
staged = "[$count ](green) "
stashed = "[](cyan) "
ahead = "⇡ "
diverged = "⇕ "
behind = "⇣ "
format = '([\[ $all_status$ahead_behind\]]($style) )'
