#!/bin/bash

export GIT_SSH_COMMAND="ssh -i ~/.dotfiles/private-dotfiles/keys/sparkleup"
cd ~/sparkleup
#git clone --depth 1 gitea@makyo.dev:makyo/hybrid
#git clone --depth 1 gitea@makyo.dev:makyo/logs
git clone --depth 1 gitea@makyo.dev:makyo/notes
git clone --depth 1 gitea@makyo.dev:makyo/task
git clone --depth 1 gitea@makyo.dev:makyo/zk
git clone --depth 1 gitea@makyo.dev:makyo/zk_html

echo <<EOF
Time to do the crontab!

0,30	*	*	*	*	/home/makyo/sparkleup/sparkleup/projects/logs
0,30    *	*	*	*	/home/makyo/sparkleup/sparkleup/projects/hybrid
*/5     *	*	*	*	/home/makyo/sparkleup/sparkleup/projects/notes
*/5     *   *   *   *   /home/makyo/sparkleup/sparkleup/projects/zk
*/5     *   *   *   *   /home/makyo/sparkleup/sparkleup/projects/task
EOF
