#!/bin/bash

# Move to the project directory and log where we are.
cd /home/makyo/sparkleup/task
pwd

# Set our SSH script.
export GIT_SSH=/home/makyo/sparkleup/sparkleup/sparkleup-ssh

# Pull any recent changes.
git pull origin master

# Push our updates.
git add .
git commit -am "update from sparkleup"
git push origin master
